### ISSUE TITLE
Add KLayout

### ISSUE THREAD

**Issue by mithro** [hdl/bazel_rules_hdl#20]
Needed for things like DRC checks and GDS generation.

**Comment by umarcor** [comment]
Ref: [hdl.github.io/awesome/items/klayout](https://hdl.github.io/awesome/items/klayout/)

**Comment by lpawelcz** [comment]
Hi, I would like to work on this one. However, It looks like we could use just the [KLayout python module](https://www.klayout.org/klayout-pypi/). This way we don't need to include to the workspace a big dependency which is Qt.

**Comment by QuantamHD** [comment]
Cool. If the python module works we can use that. Thanks for working on it.
